### ISSUE TITLE
jest?

### ISSUE THREAD

**Issue by raycohen** [transitive-bullshit/react-modern-library-boilerplate#6]
Thanks for sharing this, I've found it to be a very useful.

Would you be open to adding basic jest integration to this setup? Happy to contribute a PR if you'd like.

**Comment by transitive-bullshit** [comment]
I'd be happy to accept a PR :)

I do feel, however, that taking advantage of create-react-app's jest [integration](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#running-tests) for testing makes a lot of sense since we're already using CRA and that project has put a ton of effort into making their test suite capabilities as comprehensive as possible.

**Comment by transitive-bullshit** [comment]
Published in v1.0.10
